security:
  enableEncryption: true # Tells MongoDB to use WiredTiger
  kmip: #Tells MongoDB to use KMIP for key management and where to trust it.
    serverName: "kmip-server"
    port: 5696
    serverCAFile: /etc/pykmip/certs/ca.crt
    clientCertificateFile: /etc/pykmip/certs/client-combined.pem
    keyIdentifier: "myMasterKey"
